core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.shortcuts import redirect
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('pacientes/')),
    path('pacientes/', include('pacientes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pacientes/urls.py
from django.urls import path
from pacientes.views import pacientes, paciente_view, atualizar_paciente, excluir_consulta, consulta_publica

urlpatterns = [
    path('', pacientes, name='pacientes'),
    path('<int:id>/', paciente_view, name='paciente_view'),
    path('atualizar_paciente/<int:id>/', atualizar_paciente, name='atualizar_paciente'),
    path('excluir_consulta/<int:id>/', excluir_consulta, name='excluir_consulta'),
    path('consulta_publica/<int:id>/', consulta_publica, name='consulta_publica')
]

pacientes/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Paciente(models.Model):
    queixa_choices = (
        ('TDAH', 'TDAH'),
        ('D', 'Depressão'),
        ('A', 'Ansiedade'),
        ('O', 'Obsessão'),
        ('P', 'Pânico'),
        ('TAG', 'Transtorno de Ansiedade Generalizada'),
    )

    nome = models.CharField(max_length=255)
    email = models.EmailField()
    telefone = models.CharField(max_length=255, null=True, blank=True)
    foto = models.ImageField(upload_to='fotos')
    pagamento_em_dia = models.BooleanField(default=True)
    queixa = models.CharField(max_length=4, choices=queixa_choices)

    def __str__(self):
        return self.nome
    
class Tarefa(models.Model):
    frequencia_choices = (
        ('D', 'Diário'),
        ('1S', '1 vez por semana'),
        ('2S', '2 vezes por semana'),
        ('3S', '3 vezes por semana'),
        ('N', 'Ao necessitar')
    )

    tarefa = models.CharField(max_length=255)
    instrucoes = models.TextField()
    frequencia = models.CharField(max_length=2, choices=frequencia_choices, default='D')

    def __str__(self):
        return self.tarefa
    
class Consulta(models.Model):
    humor = models.PositiveIntegerField()
    registro_geral = models.TextField()
    video = models.FileField(upload_to='videos')
    tarefas = models.ManyToManyField(Tarefa)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.paciente.nome
    
    @property
    def link_publico(self):
        return f"http://127.0.0.1:8000{reverse('consulta_publica', kwargs={'id': self.id})}"
    
class Visualizacoes(models.Model):
    consulta = models.ForeignKey(Consulta, on_delete=models.CASCADE)
    ip = models.GenericIPAddressField()

    @property
    def views(self):
        views = Visualizacoes.objects.filter(consulta=self.consulta)
        totais = views.count()
        unicas = views.values('ip').distinct().count()
        return f'{totais} - {unicas}'

pacientes/views.py
from django.shortcuts import render, redirect
from django.http import Http404 
from django.contrib import messages
from django.contrib.messages import constants
from pacientes.models import Paciente, Tarefa, Consulta, Visualizacoes

# Create your views here.
def pacientes(request):
    if request.method == 'GET':
        pacientes = Paciente.objects.all()
        queixas = Paciente.queixa_choices
        return render(request, 'pacientes.html', {'queixas': queixas, 'pacientes': pacientes})
    elif request.method == 'POST':
        nome = request.POST.get('nome')
        email = request.POST.get('email')
        telefone = request.POST.get('telefone')
        queixa = request.POST.get('queixa')
        foto = request.FILES.get('foto')

        if len(nome.strip()) == 0 or not foto:
            messages.add_message(request, constants.ERROR, 'Nome e foto são obrigatórios.')
            return redirect('pacientes')
        
        paciente = Paciente(nome=nome, email=email, telefone=telefone, queixa=queixa, foto=foto)
        paciente.save()
        messages.add_message(request, constants.SUCCESS, 'Paciente cadastrado com sucesso.')
        return redirect('pacientes')
    
def paciente_view(request, id):
    paciente = Paciente.objects.get(id=id)
    if request.method == 'GET':
        tarefas = Tarefa.objects.all()
        consultas = Consulta.objects.filter(paciente=paciente)
        vizualizacoes = Visualizacoes.objects.filter(consulta__paciente=paciente)
        tuple_grafico = ([str(i.data) for i in consultas], [str(i.humor) for i in consultas])
        return render(request, 'paciente.html', {'paciente': paciente, 'tarefas': tarefas, 'consultas': consultas, 'vizualizacoes': vizualizacoes, 'tuple_grafico': tuple_grafico})
    elif request.method == 'POST':
        humor = request.POST.get('humor')
        registro_geral = request.POST.get('registro_geral')
        video = request.FILES.get('video')
        tarefas = request.POST.getlist('tarefas')

        consulta = Consulta(
            humor=int(humor),
            registro_geral=registro_geral,
            video=video,
            paciente=paciente
        )
        consulta.save()

        for tarefa in tarefas:
            consulta.tarefas.add(tarefa)

        consulta.save()
        messages.add_message(request, constants.SUCCESS, 'Registro de consulta cadastrada com sucesso.')
        return redirect(f'/pacientes/{id}/')
    
def atualizar_paciente(request, id):
    pagamento_em_dia = request.POST.get('pagamento_em_dia')
    paciente = Paciente.objects.get(id=id)
    status = True if pagamento_em_dia == 'ativo' else False
    paciente.pagamento_em_dia = status
    paciente.save()
    
    return redirect(f'/pacientes/{id}/')

def excluir_consulta(request, id):
    consulta = Consulta.objects.get(id=id)
    paciente_id = consulta.paciente.id
    consulta.delete()
    return redirect(f'/pacientes/{paciente_id}/')

def consulta_publica(request, id):
    consulta = Consulta.objects.get(id=id)
    if not consulta.paciente.pagamento_em_dia:
        raise Http404()
    view = Visualizacoes(
        consulta=consulta,
        ip=request.META['REMOTE_ADDR']
    )
    view.save()

    return render(request, 'consulta_publica.html', {'consulta': consulta})

pacientes/templates/consulta_publica.html
{% extends "base.html" %}

{% block 'body' %}

<div class="relative isolate">
    <svg class="pointer-events-none -z-50  absolute inset-x-0 top-0 h-[64rem] w-full stroke-gray-200 [mask-image:radial-gradient(32rem_32rem_at_center,white,transparent)]" aria-hidden="true">
    <defs>
        <pattern id="1f932ae7-37de-4c0a-a8b0-a6e3b4d44b84" width="200" height="200" x="50%" y="-1" patternUnits="userSpaceOnUse">
        <path d="M.5 200V.5H200" fill="none" />
        </pattern>
    </defs>
    <svg x="50%" y="-1" class="overflow-visible fill-gray-50">
        <path d="M-200 0h201v201h-201Z M600 0h201v201h-201Z M-400 600h201v201h-201Z M200 800h201v201h-201Z" stroke-width="0" />
    </svg>
    <rect width="100%" height="100%" stroke-width="0" fill="url(#1f932ae7-37de-4c0a-a8b0-a6e3b4d44b84)" />
    </svg>
    <div class="pointer-events-none absolute left-1/2 right-0 top-0 -z-10 -ml-24 transform-gpu overflow-hidden blur-3xl lg:ml-24 xl:ml-48" aria-hidden="true">
        <div class="aspect-[801/1036] w-[50.0625rem] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30" style="clip-path: polygon(63.1% 29.5%, 100% 17.1%, 76.6% 3%, 48.4% 0%, 44.6% 4.7%, 54.5% 25.3%, 59.8% 49%, 55.2% 57.8%, 44.4% 57.2%, 27.8% 47.9%, 35.1% 81.5%, 0% 97.7%, 39.2% 100%, 35.2% 81.4%, 97.2% 52.8%, 63.1% 29.5%)"></div>
    </div>

    <div class="py-14 sm:py-14">
        <div class="mx-auto max-w-7xl px-6 lg:px-8">
          <div class="mx-auto max-w-2xl lg:mx-0">
            <img class="size-16 rounded-full" src="{{consulta.paciente.foto.url}}" alt="">
            <p class="mt-4 text-pretty text-4xl font-semibold tracking-tight text-gray-800 sm:text-4xl">{{consulta.paciente.nome}}</p>
          </div>
        </div>
    </div>
    
    <div class="bg-slate-50 h-screen border-t-1 border-slate-200 ">
        <div class="max-w-7xl mx-auto px-6 lg:px-8 mt-6">
            
              
            <video class="w-full" controls>
                <source src="{{consulta.video.url}}" type="video/mp4">
            </video>

            <div class="mt-8">
               
                <div class="mt-8 flow-root">
                  <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
                      <table class="min-w-full divide-y divide-gray-300">
                        <thead>
                          <tr class="divide-x divide-gray-200">
                            <th scope="col" class="py-3.5 pl-4 pr-4 text-left text-sm font-semibold text-gray-900 sm:pl-0">Tarefa</th>
                            <th scope="col" class="px-4 py-3.5 text-left text-sm font-semibold text-gray-900">descrição</th>
                            <th scope="col" class="px-4 py-3.5 text-left text-sm font-semibold text-gray-900">frequencia</th>
                          </tr>
                        </thead>

                        <tbody class="divide-y divide-gray-200 bg-white">
                            {% for tarefa in consulta.tarefas.all  %}
                                <tr class="divide-x divide-gray-200">
                                    <td class="whitespace-nowrap py-4 pl-4 pr-4 text-sm font-medium text-gray-900 sm:pl-0">{{tarefa.tarefa}}</td>
                                    <td class="whitespace-nowrap p-4 text-sm text-gray-500">{{tarefa.instrucoes}}</td>
                                    <td class="whitespace-nowrap p-4 text-sm text-gray-500">{{tarefa.get_frequencia_display}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>

                      </table>
                    </div>
                  </div>
                </div>
              </div>
              

        </div>


    </div>
    
</div>


{% endblock 'body' %}

pacientes/templates/paciente.html
{% extends "base.html" %}

{% block 'body' %}

<div class="relative isolate">
    <svg class="pointer-events-none -z-50  absolute inset-x-0 top-0 h-[64rem] w-full stroke-gray-200 [mask-image:radial-gradient(32rem_32rem_at_center,white,transparent)]" aria-hidden="true">
    <defs>
        <pattern id="1f932ae7-37de-4c0a-a8b0-a6e3b4d44b84" width="200" height="200" x="50%" y="-1" patternUnits="userSpaceOnUse">
        <path d="M.5 200V.5H200" fill="none" />
        </pattern>
    </defs>
    <svg x="50%" y="-1" class="overflow-visible fill-gray-50">
        <path d="M-200 0h201v201h-201Z M600 0h201v201h-201Z M-400 600h201v201h-201Z M200 800h201v201h-201Z" stroke-width="0" />
    </svg>
    <rect width="100%" height="100%" stroke-width="0" fill="url(#1f932ae7-37de-4c0a-a8b0-a6e3b4d44b84)" />
    </svg>
    <div class="pointer-events-none absolute left-1/2 right-0 top-0 -z-10 -ml-24 transform-gpu overflow-hidden blur-3xl lg:ml-24 xl:ml-48" aria-hidden="true">
        <div class="aspect-[801/1036] w-[50.0625rem] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30" style="clip-path: polygon(63.1% 29.5%, 100% 17.1%, 76.6% 3%, 48.4% 0%, 44.6% 4.7%, 54.5% 25.3%, 59.8% 49%, 55.2% 57.8%, 44.4% 57.2%, 27.8% 47.9%, 35.1% 81.5%, 0% 97.7%, 39.2% 100%, 35.2% 81.4%, 97.2% 52.8%, 63.1% 29.5%)"></div>
    </div>

    <div class="py-14 sm:py-14">
        <div class="mx-auto max-w-7xl px-6 lg:px-8">
          <div class="mx-auto max-w-2xl lg:mx-0">
            <img class="size-16 rounded-full" src="{{paciente.foto.url}}" alt="">
            <p class="mt-4 text-pretty text-4xl font-semibold tracking-tight text-gray-800 sm:text-4xl">{{paciente.nome}}</p>
            <span class="inline-flex items-center rounded-md bg-indigo-50 px-2 py-1 text-xs font-medium text-indigo-700 ring-1 ring-inset ring-indigo-700/10">{{total_consultas}} sessões realizadas</span>
            <span class="inline-flex items-center rounded-md bg-red-50 px-2 py-1 text-xs font-medium text-red-700 ring-1 ring-inset ring-red-700/10">2 Faltas</span>
            
            <form action="{% url 'atualizar_paciente' paciente.id %}" method="POST">{% csrf_token %}
                <select name="pagamento_em_dia" class="block w-1/3 mt-4 rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                    <option value="ativo" {% if paciente.pagamento_em_dia %} selected {% endif %}>Ativo</option>
                    <option value="inativo" {% if not paciente.pagamento_em_dia %} selected {% endif %}>Inativo</option>
                </select>
                <button type="submit" class="inline-flex justify-center rounded-md bg-indigo-600 mt-4 cursor-pointer px-3 py-2  w-1/3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Atualizar</button>
            </form>

          </div>
        </div>
    </div>
    
    <div class="bg-slate-50 h-screen border-t-1 border-slate-200 ">
        <div class="max-w-7xl mx-auto px-6 lg:px-8 mt-6">
            <div class="grid grid-cols-3 gap-4">
                <div>
                    <h2 class="text-pretty text-3xl font-semibold tracking-tight text-gray-900 sm:text-4xl">Registrar consulta</h2>
                    {% if messages %}
                        {% for message in messages %}
                            <div class="rounded-md {{ message.tags }}">
                                <div class="flex">
                                    <div class="ml-3 py-4">
                                        {{ message }}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form action="{% url 'paciente_view' paciente.id %}" method="POST" enctype='multipart/form-data'>{% csrf_token %}
                        <label for="nome" class="block mt-2 text-sm/6 font-medium text-gray-600">Humor paciente</label>
                        <div class="mt-2">
                            <input type="range" name="humor" min="1" max="5" value="1" class="block w-full rounded-md text-base text-gray-900 placeholder:text-gray-400 sm:text-sm/6">
                        </div>

                        <label for="nome" class="block mt-2 text-sm/6 font-medium text-gray-600">Registro geral</label>
                        <div class="mt-2">
                            <textarea name="registro_geral" id="" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6"></textarea>
                        </div>

                        <label for="nome" class="block mt-2 text-sm/6 font-medium text-gray-600">Gravação</label>
                        <div class="mt-2">
                            <input type="file" required name="video" id="foto" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                        </div>

                        <label for="nome" class="block mt-2 text-sm/6 font-medium text-gray-600">Exercícios</label>
                        <div class="mt-2">
                            <select name="tarefas" id="" multiple class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                                
                                {% for tarefa in tarefas %}
                                    <option value="{{tarefa.id}}">{{tarefa.tarefa}}</option>
                                {% endfor %}
                             
                            </select>
                        </div>
                        <button type="submit" class="inline-flex justify-center rounded-md bg-indigo-600 mt-4 cursor-pointer px-3 py-2 w-full text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Registrar consulta</button>

                    </form>
                </div>

                <div class="mx-auto">
                    <ul role="list" class="divide-y divide-white/5">
                        {% for consulta in consultas %}
                            <li class="relative flex items-center space-x-4 py-4">
                            <div class="min-w-0 flex-auto">
                                <div class="flex items-center gap-x-3">
                                <div class="flex-none rounded-full p-1 {% if consulta.humor >= 3 %} bg-green-400/10  text-green-400 {% else %} bg-red-400/10 text-red-400 {% endif %}">
                                    <div class="size-2 rounded-full bg-current"></div>
                                </div>
                                <h2 class="min-w-0 text-sm/6 font-semibold text-slate-800">
                                    <a href="{% url 'consulta_publica' consulta.id %}" class="flex gap-x-2">
                                    <span class="truncate">{{consulta.data}}</span>
                                    
                                    </a>
                                </h2>
                                </div>
                                <div class="mt-3 flex items-center gap-x-2.5 text-xs/5 text-gray-400">
                                <p class="truncate">{{consulta.link_publico}}</p>
                                <p class="whitespace-nowrap">
                                    {% for vizualizacao in vizualizacoes %}
                                        {% if vizualizacao.consulta.id == consulta.id %}
                                            {% ifchanged vizualizacao.consulta.id %}
                                                {{ vizualizacao.views }}
                                            {% endifchanged %}
                                        {% endif %}
                                    {% endfor %}
                                    
                                </p>
                                </div>
                            </div>
                                <a href="{% url 'excluir_consulta' consulta.id %}" class="flex gap-x-2">
                                    <div class="flex-none rounded-full bg-red-400/10 px-2 py-1 text-xs font-medium text-red-400 ring-1 ring-inset ring-red-400/30">excluir</div>
                                    <svg class="size-5 flex-none text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
                                        <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
                                    </svg>
                                </a>
                            </li>
                        {% endfor %}
                        
                        
                    </ul>
                      
                </div>
            </div>

            <div class="mt-4">
                <canvas id="myChart"></canvas>
              </div>
               
        </div>
    </div>
    
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    const ctx = document.getElementById('myChart');
  
    new Chart(ctx, {
      type: 'line',
      data: {
        labels: {{tuple_grafico.0|safe}},
        datasets: [{
          label: 'Humor do paciente',
          data: {{tuple_grafico.1|safe}},
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
</script>

{% endblock 'body' %}

pacientes/templates/pacientes.html
{% extends "base.html" %}

{% block 'body' %}
    <div class="relative isolate">
        <svg class="pointer-events-none -z-50  absolute inset-x-0 top-0 h-[64rem] w-full stroke-gray-200 [mask-image:radial-gradient(32rem_32rem_at_center,white,transparent)]" aria-hidden="true">
        <defs>
            <pattern id="1f932ae7-37de-4c0a-a8b0-a6e3b4d44b84" width="200" height="200" x="50%" y="-1" patternUnits="userSpaceOnUse">
            <path d="M.5 200V.5H200" fill="none" />
            </pattern>
        </defs>
        <svg x="50%" y="-1" class="overflow-visible fill-gray-50">
            <path d="M-200 0h201v201h-201Z M600 0h201v201h-201Z M-400 600h201v201h-201Z M200 800h201v201h-201Z" stroke-width="0" />
        </svg>
        <rect width="100%" height="100%" stroke-width="0" fill="url(#1f932ae7-37de-4c0a-a8b0-a6e3b4d44b84)" />
        </svg>
        <div class="pointer-events-none absolute left-1/2 right-0 top-0 -z-10 -ml-24 transform-gpu overflow-hidden blur-3xl lg:ml-24 xl:ml-48" aria-hidden="true">
            <div class="aspect-[801/1036] w-[50.0625rem] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30" style="clip-path: polygon(63.1% 29.5%, 100% 17.1%, 76.6% 3%, 48.4% 0%, 44.6% 4.7%, 54.5% 25.3%, 59.8% 49%, 55.2% 57.8%, 44.4% 57.2%, 27.8% 47.9%, 35.1% 81.5%, 0% 97.7%, 39.2% 100%, 35.2% 81.4%, 97.2% 52.8%, 63.1% 29.5%)"></div>
        </div>
    

    <div class="py-24 sm:py-32">
        <div class="mx-auto grid max-w-7xl gap-20 px-6 lg:px-8 xl:grid-cols-3">
          <div class="max-w-xl">
           
            <h2 class="text-pretty text-3xl font-semibold tracking-tight text-gray-900 sm:text-4xl">Cadastre pacientes</h2>

            
            {% if messages %}
                {% for message in messages %}
                    <div class="rounded-md {{ message.tags }}">
                        <div class="flex">
                            <div class="ml-3 py-4">
                                {{ message }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
                
            
            <form action="{% url 'pacientes' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <label for="nome" class="block mt-2 text-sm/6 font-medium text-gray-600">Nome</label>
                <div class="mt-2">
                    <input type="text" name="nome" id="nome" autocomplete="given-name" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                </div>

                <label for="email" class="block mt-2 text-sm/6 font-medium text-gray-600">Email</label>
                <div class="mt-2">
                    <input type="email" name="email" id="email" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                </div>

                <label for="telefone" class="block mt-2 text-sm/6 font-medium text-gray-600">Telefone</label>
                <div class="mt-2">
                    <input type="text" name="telefone" id="telefone" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                </div>

                <div class="grid grid-cols-2 gap-2">
                    <div>
                        <label for="telefone" class="block mt-2 text-sm/6 font-medium text-gray-600">Queixa</label>
                        <div class="mt-2">
                            <select name="queixa" class="block w-full rounded-md bg-white px-3 py-2 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                                
                                {% for queixa in queixas %}
                                    <option value="{{ queixa.0 }}">{{ queixa.1 }}</option>
                                {% endfor %}
                                
                            </select>
                            
                        </div>
                    </div>

                    <div>
                        <label for="foto" class="block mt-2 text-sm/6 font-medium text-gray-600">Foto</label>
                        <div class="mt-2">
                            <input type="file" required name="foto" id="foto" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                        </div>
                    </div>
                    
                </div>
                <button type="submit" class="inline-flex justify-center rounded-md bg-indigo-600 mt-4 cursor-pointer px-3 py-2 w-full text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Cadastrar paciente</button>
            </form>
        </div>
            <ul role="list" class="grid gap-x-8 gap-y-12 sm:grid-cols-2 sm:gap-y-16 xl:col-span-2">
            {% for paciente in pacientes %}
                <li>
                <div class="flex items-center gap-x-6">
                    <img class="size-16 rounded-full" src="{{ paciente.foto.url }}" alt="">
                    <div>
                    <a href="{% url 'paciente_view' paciente.id %}" class="text-base/7 font-semibold tracking-tight text-gray-900">{{ paciente.nome }}</a>
                    <p class="text-sm/6 font-semibold text-indigo-600">{{ paciente.queixa }}</p>
                    </div>
                </div>
                </li>
            {% endfor %}
        
            
  
            </ul>
        </div>
      </div>
      
    </div>


{% endblock 'body' %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/@tailwindcss/browser@4"></script>
    {% block 'head' %}{% endblock 'head' %}
</head>
<body>
    <header class="bg-slate-50">
        <nav class="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
          <div class="flex lg:flex-1">
            <a href="#" class="-m-1.5 p-1.5">
              <img class="h-8 w-auto" src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=600" alt="">
            </a>
          </div>
          <div class="flex lg:hidden">
            <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
              <span class="sr-only">Open main menu</span>
              <svg class="size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
              </svg>
            </button>
          </div>
          <div class="hidden lg:flex lg:gap-x-12">
            <a href="{% url 'pacientes' %}" class="text-sm/6 font-semibold text-gray-900">Pacientes</a>
          </div>
          <div class="hidden lg:flex lg:flex-1 lg:justify-end">

          </div>
        </nav>
    
      </header>

    {% block 'body' %}{% endblock 'body' %}
</body>
</html>